### ISSUE TITLE
Class conflict with SonarQube (7.7) editions other than Community Edition

### ISSUE THREAD

**Issue by michaeljsnyder** [fortify-ps/fortify-integration-sonarqube#4] opened 2019-06-06 23:49 UTC
It looks like SonarQube 7.7 ships with javax.ws.rs-api-2.1, while fortify-client-api ships with jakarta.ws.rs.api-2.1.5. This results in a stack trace when trying to use the plugin:

> java.lang.LinkageError: ClassCastException: attempting to castjar:file:/sonarqube-7.7/lib/common/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/sonarqube-7.7/temp/ce-exploded-plugins/fortify/META-INF/lib/jakarta.ws.rs-api-2.1.5.jar!/javax/ws/rs/client/ClientBuilder.class
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:109)
	at com.fortify.util.rest.connection.AbstractRestConnection.createClient(AbstractRestConnection.java:653)
	at com.fortify.util.rest.connection.AbstractRestConnection.getClient(AbstractRestConnection.java:589)
	at com.fortify.util.rest.connection.AbstractRestConnection.getBaseResource(AbstractRestConnection.java:553)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.getWebTarget(AbstractRestConnectionQuery.java:116)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.getUnique(AbstractRestConnectionQuery.java:104)
	at com.fortify.integration.sonarqube.common.source.ssc.ce.FortifySSCConfigurableMeasureComputer.getConfigurableMeasuresInputData(FortifySSCConfigurableMeasureComputer.java:77)
	at com.fortify.integration.sonarqube.common.source.ssc.ce.FortifySSCConfigurableMeasureComputer.getConfigurableMeasuresInputData(FortifySSCConfigurableMeasureComputer.java:42)
	at com.fortify.integration.sonarqube.common.ce.AbstractFortifyConfigurableMeasureComputer.compute(AbstractFortifyConfigurableMeasureComputer.java:94)
	at com.fortify.integration.sonarqube.common.ce.AbstractFortifyMeasureComputerWithConnectionHelper.compute(AbstractFortifyMeasureComputerWithConnectionHelper.java:83)
	at org.sonar.ce.task.projectanalysis.measure.MeasureComputersVisitor.visitAny(MeasureComputersVisitor.java:65)
	at org.sonar.ce.task.projectanalysis.component.TypeAwareVisitorWrapper.visitAny(TypeAwareVisitorWrapper.java:77)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitNode(VisitorsCrawler.java:117)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:100)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:72)
	at org.sonar.ce.task.projectanalysis.step.ExecuteVisitorsStep.execute(ExecuteVisitorsStep.java:51)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:207)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:189)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:156)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:131)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:83)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rsenden** [comment] 2019-06-07 07:03
Which SonarQube variant are you using? I downloaded SonarQube 7.7 Community Edition just now; it does not contain javax.ws.rs-api-2.1.jar and the Fortify plugin runs without any issues. 

Can you verify that javax.ws.rs-api-2.1.jar comes actually bundled with your SonarQube variant, and this jar-file was not added after SonarQube was installed?

I don't have a license for any of the other SonarQube variants, this may make it difficult to implement and test a fix for this issue if those variants indeed ship with additional jar-files.

**Comment by michaeljsnyder** [comment] 2019-06-07 10:35
Thanks for the quick response @rsenden. I had assumed that all versions of SonarQube would use the same base libraries, but was wrong. My team is using Enterprise Edition.

I just downloaded fresh copies of all three editions, and it looks like Community Edition does not include javax.ws.rs-api-2.1.jar, but both Developer Edition and Enterprise Edition do. Removing the jar from our deployment prevents SonarQube from launching, so it's definitely required by the higher editions.

Apologies for pushing this back your way, but it looks like you could get a trial license for either/both Developer Edition or Enterprise Edition. My team did this when we were evaluating SonarQube and they were pretty quick to respond.

https://www.sonarsource.com/plans-and-pricing/developer/

https://www.sonarsource.com/plans-and-pricing/enterprise/

Aside from that, I'm happy to help debug further in whatever way I can.

Edit: It might be possible to reproduce this without a license by just copying javax.ws.rs-api-2.1.jar from either the Developer or Enterprise Edition (inside /lib/common/) over to the same folder in a Community Edition install. That might be enough to introduce the conflict on the classpath, regardless of whether SonarQube actually uses it?

**Comment by rsenden** [comment] 2019-06-07 12:55
The plugin uses the child-first class loading strategy, so in general any jars provided by SonarQube shouldn't cause any issues with the Fortify plugin. 

Given some Google searches on similar issues, it looks like SonarQube doesn't properly set the thread context class loader when invoking plugins that use child-first class loading strategy. As such, any libraries that use the thread context class loader (like JAX-RS) will try to load classes from the parent (SonarQube) class loader, instead of loading these classes from the child (plugin) class loader.

A possible solution could be to explicitly set the thread context class loader before calling any code that depends on the thread context class loader, and restore the original thread context class loader afterwards, something like the following:

```
    	ClassLoader oldCl = Thread.currentThread().getContextClassLoader();
    	try {
    		Thread.currentThread().setContextClassLoader(CurrentClass.class.getClassLoader());
	        // invoke method that depends on context class loader being set to the child class loader
    	} finally {
    		Thread.currentThread().setContextClassLoader(oldCl);
    	}
```

I'll need to think about the best place to do this though (somewhere in the SonarQube Fortify plugin or in the generic fortify-client-api library), and then test whether this actually resolves this issue (potentially using your suggestion of just copying the JAX-RS jar to the lib/common folder  of SonarQube Community Edition).

Due to other commitments I'm not sure though when I'll have time to look into this. If you want to reserve some dedicated time for me to look into this issue in more detail, please consider purchasing Fortify Professional Services by contacting your Fortify sales representative.

Of course, since this is an open source project, you could also try to fix this issue yourself based on the information provided above, if you have any experienced Java developers around.

**Comment by michaeljsnyder** [comment] 2019-06-08 18:06
Thanks @rsenden; Java is definitely not my primary language so your insight and background on the issue was much appreciated.

I was able to resolve this for our installation by wrapping the compute() call in AbstractFortifyMeasureComputerWithConnectionHelper.compute() here:

https://github.com/fortify-ps/fortify-integration-sonarqube/blob/master/plugin/src/main/java/com/fortify/integration/sonarqube/common/ce/AbstractFortifyMeasureComputerWithConnectionHelper.java#L83

With the class loader try/catch above. I'm happy to submit a PR for this, but I expect that it's not the only place where we'd need to guard against this, and that there's probably a better, more-centralized spot to handle it.

Ideally I think this should be addressed by SonarQube, rather than forcing each plugin to guard itself. I'll reach out to them as well.

**Comment by rsenden** [comment] 2019-06-10 09:23
Good to hear that setting the context class loader resolves this issue. Indeed it would be best to have this addressed by SonarQube; ideally every call from SonarQube to any plugin code should have the context class loader correctly set. Anyway I'll need to provide a work-around until they get this fixed.

Given your feedback, it seems that only plugin code running on the SonarQube server side is affected by this issue; probably the scanner side doesn't include the conflicting library.

As such, you probably implemented this fix at the most optimal location, as this `compute()` call wraps most of the plugin code that is executed on the server side. 

To be on the safe side though, probably every plugin method that can be directly invoked from SonarQube should be wrapped in a try/finally block, in order to make sure that all plugin code is executed with the correct context class loader.

For example, if for any reason the JAX-RS jar is added to the class path on the scanner side (in a future SonarQube version, user overriding the default class path, ...), then the scanner side of the plugin would probably fail as well.

I'll have a look into this as time permits.

**Comment by rsenden** [comment] 2019-06-10 12:28
I checked in some changes as a first attempt for a generic solution for this issue. It still needs some work, but are you able to try to build the plugin from the latest sources on the master branch, and see whether it resolves your original issue?

Note that this version spits out some debugging information to standard out (on both server and scanner side) whenever SonarQube invokes a plugin method; this will be removed when I finalize the fix.

I'll try to finalize this later this week.

**Comment by michaeljsnyder** [comment] 2019-06-10 13:37
Awesome, thanks! I just rebuilt the plugin from master and re-ran our SonarQube scan without issues. Looks like your changes resolved the issue on the server side. Definitely appreciate the assistance with this!

**Comment by rsenden** [comment] 2019-06-10 23:34
A pre-release containing the potential fix is now available at https://github.com/fortify-ps/fortify-integration-sonarqube/releases/tag/2.5. 

I am unable to reproduce the issue by copying the conflicting JAR into the common/lib directory of SonarQube Community Edition, so can you please (thoroughly) test this new pre-release with your SonarQube edition and let me know the results?

I'll mark the release as an official release if there are no remaining issues.

**Comment by michaeljsnyder** [comment] 2019-06-12 00:21
Everything looks great on my end @rsenden. I ran dozens of builds through our pipeline today and had no issues pushing results to SonarQube, nor reviewing them in dashboards. As far as I can tell this class loader issue is now fixed/safeguarded.

Thank you again very much for prioritizing work on this issue, it's much appreciated by my entire team.

**Comment by rsenden** [comment] 2019-06-12 07:44
Thanks again for the feedback, good to hear everything now works as expected.

**Closed as completed by rsenden** 2019-06-12 07:44 UTC
